version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - npm
      - dependencies
      - autorebase:opt-in

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - bundler
      - dependencies
      - autorebase:opt-in

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - github-actions
      - dependencies
      - autorebase:opt-in
