version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
