version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
  - package-ecosystem: "bundler"
    directory: "/"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
