FROM internetee/ruby_base:3.0-v6
LABEL org.opencontainers.image.source=https://github.com/internetee/auction_center
ARG RAILS_ENV
ARG SECRET_KEY_BASE

ENV RAILS_ENV "$RAILS_ENV"
ENV SECRET_KEY_BASE "$SECRET_KEY_BASE"


COPY Gemfile Gemfile.lock ./    
RUN gem install bundler && bundle config set without 'development test' && bundle install --jobs 20 --retry 5
RUN yarn install --check-files

COPY . .

RUN bundle exec rails assets:precompile
