development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { AuctionCenter::Application.config.customization[:cable_redis_url] } %>
  channel_prefix: auction_center_development

test:
  adapter: async

staging:
  url: <%= ENV.fetch("REDIS_CABLE_URL") { AuctionCenter::Application.config.customization[:cable_redis_url] } %>
  adapter: redis
  channel_prefix: auction_center_staging

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { AuctionCenter::Application.config.customization[:cable_redis_url] } %>
  channel_prefix: auction_center_production
