// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
// import Rails from "@rails/ujs"

import HelloController from "./hello_controller"
application.register("hello", HelloController)
import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)
import CheckController from "./check_controller"
application.register("check", CheckController)
import SubmitterController from "./submitter_controller"
application.register("submitter", SubmitterController)
import CheckerController from "./checker_controller"
application.register("checker", CheckerController)
import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)
import WishlistController from "./wishlist_controller"
application.register("wishlist", WishlistController)
import AuctionTypeHandlerController from "./auction_type_handler_controller"
application.register("auction_type_handler", AuctionTypeHandlerController)
import CheckboxToggleController from "./checkbox_toggle_controller"
application.register("checkbox_toggle", CheckboxToggleController)
import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)